language: julia
os:
  - linux
  - osx
julia:
  - 1.1
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'using Pkg; end; Pkg.clone(pwd()); Pkg.build("Bobby"); Pkg.test("Bobby"; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Bobby")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
matrix:
  fast_finish: true